version: '3'

services:
  nest:
    build:
      context: ./home/aymen/Desktop/nest
      dockerfile: Dockerfile
    container_name: nest_dev
    volumes:
      - /home/aymen/Desktop/nest:/usr/src/app
    ports:
      - "3002:3002"
    depends_on:
      - consul
      - jaeger
    environment:
      - CHOKIDAR_USEPOLLING=true

  departement:
    image: aymena26/dep:1
    ports:
      - "9001:9001"
    depends_on:
      - consul
      - jaeger

  api:
    image: aymena26/apigat:1
    ports:
      - "8082:8082"
    depends_on:
      - consul
      - jaeger

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  user:
    image: aymena26/user:1
    ports:
      - "9003:9003"
    depends_on:
      - consul
      - jaeger

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # Jaeger agent UDP port
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Jaeger collector
