version: '3'
services:
  user:
    image: aymena26/user:1
    ports:
      - "9003:9003"
    depends_on:
      - consul

  departement:
    image: aymena26/dep:1
    ports:
      - "9001:9001"
    depends_on:
      - consul

  api:
    image: aymena26/apigat:1
    ports:
      - "8082:8082"
    depends_on:
      - consul

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./path/to/your/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
