global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user:9003']

  - job_name: 'departement-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['departement:9001']

  - job_name: 'api-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8082']

